name: Add new sources of input to the chat model

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'open-machine-learning-jupyter-book/**'

jobs:
  update-vector-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Use the Get-ChildItem cmdlet to search for md files and output them to a file
      - name: Find MD files
        run: |
          find . -type f -name "*.md" > md_files.txt

      # Upload the md_files.txt file as an artifact
      - name: Upload MD files artifact
        uses: actions/upload-artifact@v2
        with:
          name: md_files
          path: md_files.txt

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Update the vector database of chatbot using Python script
      - name: Update vector database of chatbot
        env:
          MD_FILES: ${{ steps.find-md-files.outputs.stdout }}
        run: |
          python chatbot/workflows/update_vectordb.py --md_files $MD_FILES