name: update the source links in online book

on:
  push:
    branches:
    - release
    paths:
    - open-machine-learning-jupyter-book/**
    - .github/**
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  build-chatbot:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the repository to get access to the files.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-deepth: 0 # Fetch complete history.

      # Set up Node.js 16.x.
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      # Set up Python.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies.
      - name: Install dependencies
        run: |
          npm install dotenv
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install openai
          python -m pip install qdrant_client
          python -m pip install langchain
          python -m pip install tiktoken
          python -m pip install python-dotenv

      # Get changed files.
      - name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep 'open-machine-learning-jupyter-book' | grep '\.md$')"

      # Write changed files to a text file.
      - name: Write changed files to a text file
        run: |
          for file in ${{ steps.getfile.outputs.files }}; do
            echo "https://github.com/open-academy/machine-learning/blob/${{ github.ref }}/${file}" >> ./chatbot/vector-db-persist-directory/resources-new/changed_file.txt
          done
          echo  "hello" >> ./chatbot/vector-db-persist-directory/resources-new/changed_file.txt
      
      # Commit and push changes.
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --cached --quiet || git add ./chatbot/vector-db-persist-directory/resources-new/changed_file.txt
          git diff --cached --quiet || git commit -m "Update changed files list" -a
          git diff --cached --quiet || git push

      # Set up OpenAI API Key.
      - name: Set up OpenAI API Key
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Set up OpenAI API Key successfully."
          
      # Update the vector database of chatbot using Python script.
      - name: Update the vector database of chatbot
        run: python -m chatbot.workflows.update_source_link
