name: update the source links in online book

on:
  push:
    branches:
    - release
    paths:
    - open-machine-learning-jupyter-book/**
    - .github/**
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  build-chatbot:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the repository to get access to the files.
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js 16.x.
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      # Set up Python.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up OpenAI API Key
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Set up OpenAI API Key successfully."
          
      # Update the vector database of chatbot using Python script.
      - name: Update the vector database of chatbot
        run: python chatbot/workflows/update_source_link.py
